# application.properties
spring.profiles.active=docker

# Configuration commune
spring.main.allow-bean-definition-overriding=true

# i18n Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
