
package ca.deltagis.success.v1.adapters.web.message;

import ca.deltagis.success.v1.adapters.web.message.files.FileUploadError;

public enum ProjectMessage {
    ALREADY_EXISTS("ALREADY_EXISTS"),
    ACTIVE("ACTIVE"),
    NONE("NONE"),
    NOT_FOUND("NOT_FOUND"),
    ALREADY_ACTIVE("ALREADY_ACTIVE"),
    PROJECT_EXISTS("PROJECT_EXISTS"),
    PROJECT_NOT_FOUND("PROJECT_NOT_FOUND"),
    INVALID_DATA("INVALID_DATA"),
    NOT_STARTED("NOT_STARTED"),
    STARTED_SUCCESSFULLY("STARTED_SUCCESSFULLY"),
    NOT_COMPLETED("NOT_COMPLETED"),
    ALREADY_SUSPENDED("ALREADY_SUSPENDED"),
    SUSPENDED("SUSPENDED"),
    ARCHIVED("ARCHIVED"),
    DISABLED("DISABLED"),
    ALREADY_DISABLED("ALREADY_DISABLED"),
    AlREADY_ARCHIVED("AlREADY_ARCHIVED"),
    ALREADY_CLOSED("ALREADY_CLOSED"),
    CANT_UPDATE_DELETED_PROJECT("CANT_UPDATE_DELETED_PROJECT"),
    SOMETHING_WENT_WRONG("SOMETHING_WENT_WRONG"),
    WORKSPACE_NOT_FOUND("WORKSPACE_NOT_FOUND"),
    WORKSPACE_DELETED("WORKSPACE_DELETED"),
    CANT_UPLOAD_EMPTY_FILE("CANT_UPLOAD_EMPTY_FILE"),
    ERROR_STATUS("ERROR_STATUS"),
    UPLOAD_FAILED("UPLOAD_FAILED"),
    UPLOAD_INVALID_DESTINATION("UPLOAD_INVALID_DESTINATION"),
    NO_IMAGES("NO IMAGES AVAILABLE"),
    DELETE_FILE("YOUR FILE HAS BEEN DELETED");
    private final String value;

    ProjectMessage(String value) {
        this.value = value;
    }

     public static ProjectMessage fromFileUploadError(FileUploadError error) {
        return switch (error) {
            case EMPTY_FILE -> CANT_UPLOAD_EMPTY_FILE;
            case INVALID_DESTINATION_PATH -> UPLOAD_INVALID_DESTINATION;
            case FAILED_TO_SAVE_FILE -> UPLOAD_FAILED;
            default -> SOMETHING_WENT_WRONG;
        };
    }
}