package com.erastedev.ciexplore.v1.adapters.web.message;

public enum ExerciceMessage {
    ALREADY_EXISTS("YOUR PROJECT IS ALREADY EXISTE"),
    NOT_FOUND("NOT_FOUND"),
    STARTED_SUCCESSFULLY("STARTED_SUCCESSFULLY"),
    ALREADY_SUSPENDED("ALREADY_SUSPENDED"),
    ALREADY_PENDING("YOUR EXERCICE IS ALREADY PENDING"),
    NONE("NONE"),
    SOMETHING_WENT_WRONG("SOMETHING WENT WRONG"),
    UPDATED("EXERCICE UPDATED"),
    NOT_UPDATED("MODIFICATION IMPOSSIBLE PLEASE CHECK THE STATUS OF THE EXERCICE PLEASE"),
    PROJECT_NOT_FOUND("PROJECT NOT FOUND"),
    NOT_STARTED("NOT_STARTED"),
    LATER_EXERCISES("LATER EXERCICES ARE ALREADY DEFINED"),
    INVALID_START_DATE("THE START DATE OF THE NEW FINANCIAL YEAR CANNOT EXCEED THAT OF THE LAST FINANCIAL YEAR CREATED BY MORE THAN 1 YEAR."),
    EXERCICE_NOT_INCLUD("EXERCISE IS NOT INCLUDED IN THE PROJECT EXECUTION PERIOD");

    private final String value;
    
    ExerciceMessage(String value) {
        this.value = value;
    }




}
